// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjpomxvtvsitoylqvzvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqcG9teHZ0dnNpdG95bHF2enZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjk0NzMsImV4cCI6MjA2NjYwNTQ3M30.J7SGjVjjmX_Kb0fqkFPzgp1jBFzC8WNZYRbatjxEP-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});